### ISSUE TITLE
Reactions menu isn't textured and is out of place

### ISSUE THREAD

**Issue by Lifell** [codedotspectra/dunes#1]
Screeenshot explains it :]
![tjah](https://user-images.githubusercontent.com/26024918/48874090-af5fea00-edf1-11e8-9214-73ba1109985f.png)

**Comment by codedotspectra** [comment]
should be fixed

**Comment by Lifell** [comment]
It doesn't seem to work still. I tried turning all plugins off in case that was interfering and reinstalling BandagedBD with their new installer but it still shows it like that. I go and see if an option in BD itself is causing the issue.
